// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB62-cexREbpl4z1x0YexGRyEBuGNTZ8i0',
    appId: '1:558328010736:web:a45021ada9063d67352f35',
    messagingSenderId: '558328010736',
    projectId: 'savoir-7b668',
    authDomain: 'savoir-7b668.firebaseapp.com',
    storageBucket: 'savoir-7b668.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZFZyuxJ_R9qTKdKFkKpCFBLNOyQnA9aw',
    appId: '1:558328010736:android:282e75d1877e335c352f35',
    messagingSenderId: '558328010736',
    projectId: 'savoir-7b668',
    storageBucket: 'savoir-7b668.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWOVfFMhilP2EMUPlPOTgpKgntcnbhPL4',
    appId: '1:558328010736:ios:c644a59a6d92f7da352f35',
    messagingSenderId: '558328010736',
    projectId: 'savoir-7b668',
    storageBucket: 'savoir-7b668.firebasestorage.app',
    iosBundleId: 'com.example.savoir',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWOVfFMhilP2EMUPlPOTgpKgntcnbhPL4',
    appId: '1:558328010736:ios:c644a59a6d92f7da352f35',
    messagingSenderId: '558328010736',
    projectId: 'savoir-7b668',
    storageBucket: 'savoir-7b668.firebasestorage.app',
    iosBundleId: 'com.example.savoir',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB62-cexREbpl4z1x0YexGRyEBuGNTZ8i0',
    appId: '1:558328010736:web:12b835f094344216352f35',
    messagingSenderId: '558328010736',
    projectId: 'savoir-7b668',
    authDomain: 'savoir-7b668.firebaseapp.com',
    storageBucket: 'savoir-7b668.firebasestorage.app',
  );
}
